spring:
  application:
    name: configuration-server
    instance_id: 1
  cloud:
    config:
      server:
        git:
          uri: /Users/cem/Developer/Workspace/ms-test-related/configrepo

eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8888
